package com.hy.common.model;


import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {

		/*
		* 系统部分
		* */
		arp.addMapping("sys_company", "id", Company.class);
		arp.addMapping("sys_dept", "id", Dept.class);
		arp.addMapping("sys_deviceclass", "id", Deviceclass.class);
		arp.addMapping("sys_devicelist", "id", Devicelist.class);
		arp.addMapping("sys_dict", "id", Dict.class);
		arp.addMapping("sys_login_log", "id", LoginLog.class);
		arp.addMapping("sys_menu", "id", Menu.class);
		arp.addMapping("sys_operation_log", "id", OperationLog.class);
		arp.addMapping("sys_parameter", "id", Parameter.class);
		arp.addMapping("sys_partner", "id", Partner.class);
		arp.addMapping("sys_role_menu", "id", RoleMenu.class);
		arp.addMapping("sys_user_role", "id", UserRole.class);
		arp.addMapping("sys_roles", "id", Roles.class);
		arp.addMapping("sys_session", "id", Session.class);
		arp.addMapping("sys_user", "id", User.class);
		/*
		* 计划部分
		* */
		arp.addMapping("plan_apply", "id", Apply.class);
		arp.addMapping("plan_applybenefit", "id", Applybenefit.class);
		arp.addMapping("plan_applyinfor", "id", Applyinfor.class);
		arp.addMapping("plan_applypartner", "id", Applypartner.class);
		arp.addMapping("plan_task", "id", PlanTask.class);
		/**
		* 库房部分
		**/
		arp.addMapping("stock_warehouse", "id", Warehouse.class);
		arp.addMapping("stock_deptstock", "id", Deptstock.class);
		arp.addMapping("stock_leavestock", "id", LeaveStock.class);
		arp.addMapping("stock_enterstock", "id", Enterstock.class);
		arp.addMapping("stock_enterstock_detail", "id", EnterstockDetail.class);
		arp.addMapping("stock_leavestock_detail", "id", LeaveStockDetail.class);
		arp.addMapping("stock_stockpile", "id", Stockpile.class);
		arp.addMapping("stock_stockpile_subinfor", "id", Stockpilesubinfor.class);
		arp.addMapping("stock_stockpile_subpart", "id", Subpart.class);
		arp.addMapping("stock_stockpile_subservice", "id", Subservice.class);
		arp.addMapping("stock_stockpile_servicerecord", "id",Servicerecord.class);
		arp.addMapping("stock_inoutrecord", "id", Inoutrecord.class);
		arp.addMapping("stock_install", "id", Install.class);
		arp.addMapping("stock_repair", "id", Repair.class);
		arp.addMapping("stock_upkeep", "id", Upkeep.class);
		arp.addMapping("stock_allot", "id", Allot.class);
		arp.addMapping("stock_allot_detail", "id", AllotDetail.class);

		/**
		* 采购部门
		**/
		arp.addMapping("purchase_purchasetask", "id", PurchaseTask.class);
		arp.addMapping("purchase_purchasetask_detail", "id", PurchaseTaskDetail.class);


		/**
		* 设备科管理
		**/
		arp.addMapping("plan_task", "id", EngineerManage.class);
		arp.addMapping("plan_task", "id", DispatchManage.class);
		arp.addMapping("plan_task", "id", DocumentManage.class);
		arp.addMapping("plan_task", "id", DepartmentManage.class);

		/**
		 * 日常业务
		 **/
		arp.addMapping("plan_task", "id", InstallManage.class);
		arp.addMapping("plan_task", "id", RepairManage.class);
		arp.addMapping("plan_task", "id", MaintainManage.class);
		arp.addMapping("plan_task", "id", QualityManage.class);
		arp.addMapping("plan_task", "id", BadManage.class);
	}
}


