package com.hy.common.model;

import com.hy.common.model.base.BaseAllot;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Allot extends BaseAllot<Allot> {
	
	    private Integer id ; //
	    private Integer allotId ; //
	    private String allotType ; //
	    private String fromStock ; //
	    private String toStock ; //
	    private Integer num ; //
	    private Double price ; //
	    private Integer userId ; //
	    private java.util.Date time ; //

}
