package com.hy.common.model;

import com.hy.common.model.base.BaseAllotDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AllotDetail extends BaseAllotDetail<AllotDetail> {
	
	    private Integer id ; //
	    private String place ; //
	    private Integer fileNumber ; //
	    private String deviceName ; //
	    private String modle ; //
	    private Double price ; //
	    private String agency ; //
	    private String company ; //
	    private String brund ; //

}
