package com.hy.common.model;


import com.hy.common.model.base.BaseApplybenefit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Applybenefit extends BaseApplybenefit<Applybenefit> {
	
	    private Integer id ; //
	    private Integer applyId ; //
	    private String useYear ; //
	    private String useWeek ; //
	    private String charge ; //
	    private String income ; //
	    private String cost ; //
	    private String recoveryTime ; //
	    private String sampleNumber ; //
	    private String peopleTimes ; //

}
