package com.hy.common.model;

import com.hy.common.model.base.BaseApply;
import com.jfinal.plugin.activerecord.Record;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Apply extends BaseApply<Apply> {
	
	    private Integer id ; //
	    private String planType ; //
	    private String planName ; //
	    private String Code ; //
	    private Integer deptId ; //
	    private Integer userId ; //
	    private String deviceNumber ; //
	    private String unit ; //
	    private String deviceId ; //
	    private java.util.Date purchaseDate ; //
	    private Double budget ; //
	    private String capitalSource ; //
	    private String applyReason ; //
	    private String userDept ; //
	    private java.util.Date createTime ; //
	    private String status ; //
	    private Integer auditor ; //
	    private String auditOpinion ; //
	    private java.util.Date auditTime ; //
		private String enName ; //
		private String cnName ; //
	//申请表的子表 applyPartner
	private List<Record> applyPartnerLst;
	//申请表的子表 applybenefit
	private Record applybenefit;
	//申请表的子表 applyinfor
	private Record applyinfor;
	//申请表的连表 applyinfor
	private List<Record> device;
	//申请表的连表 applyinfor
	private Record user;
	//申请表的连表 applyinfor
	private Record dept;


	public List<Record> getDevice() {
		return device;
	}

	public void setDevice(List<Record> device) {
		this.device = device;
	}



	public Record getUser() {
		return user;
	}

	public void setUser(Record user) {
		this.user = user;
	}

	public Record getDept() {
		return dept;
	}

	public void setDept(Record dept) {
		this.dept = dept;
	}

	public List<Record> getApplyPartnerLst() {
		return applyPartnerLst;
	}

	public void setApplyPartnerLst(List<Record> applyPartnerLst) {
		this.applyPartnerLst = applyPartnerLst;
	}

	public Record getApplybenefit() {
		return applybenefit;
	}

	public void setApplybenefit(Record applybenefit) {
		this.applybenefit = applybenefit;
	}

	public Record getApplyinfor() {
		return applyinfor;
	}

	public void setApplyinfor(Record applyinfor) {
		this.applyinfor = applyinfor;
	}



}
