package com.hy.common.model;


import com.hy.common.model.base.BaseApplypartner;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Applypartner extends BaseApplypartner<Applypartner> {

	private java.lang.Integer id ; //
	private java.lang.Integer applyId ; //
	private java.lang.String brand ; //
	private java.lang.String models ; //
	private java.lang.String way ; //

}

