package com.hy.common.model;

import com.hy.common.model.base.BaseApplyinfor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Applyinfor extends BaseApplyinfor<Applyinfor> {
	
}
