package com.hy.common.model;

import com.hy.common.model.base.BaseDeptstock;
import com.hy.common.model.base.BaseDeptstock;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Deptstock extends BaseDeptstock<Deptstock> {
	
	    private Integer id ; //
	    private String fileNumber ; //
	    private Integer deptId ; //
	    private Integer storehouseId ; //
	    private Integer deviceId ; //
	    private java.util.Date enterDate ; //
	    private Integer number ; //
	    private Double price ; //
	    private java.util.Date productDate ; //
	    private Integer useTime ; //
	    private Integer bathnum ; //
	    private Integer propertyId ; //
	    private String code ; //
	    private String period ; //
	    private Integer stockId ; //
	    private String deviceName ; //
	    private String deviceClassName ; //

}
