package com.hy.common.model;

import com.hy.common.model.base.BaseDept;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dept extends BaseDept<Dept> {
	
	    private Integer id ; //
	    private Integer num ; //
	    private Integer pid ; //
	    private String simpleName ; //
	    private String fullName ; //
	    private String tips ; //
	    private Integer version ; //

}
