package com.hy.common.model;

import com.hy.common.model.base.BaseDeviceclass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Deviceclass extends BaseDeviceclass<Deviceclass> {
    private Integer id ; //
    private String sn ; //
    private String name ; //
    private String simpleCode ; //
    private Integer pid ; //
    private Integer num ; //
    private String status ; //
}
