package com.hy.common.model;

import com.hy.common.enumresource.StateEnum;
import com.hy.common.model.base.BaseDevicelist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Devicelist extends BaseDevicelist<Devicelist> {
    private Integer id ; //
    private String cnName ; //
    private String simpleName ; //
    private String enName ; //
    private Integer classId ; //
    private String brand ; //
    private String type ; //
    private String unit ; //
    private String createTime ; //
    private Integer otherCompanyID ; //
    private String status ; //
    private Integer deleted;
    private Deviceclass deviceClass;
    private Partner partner;
    private StateEnum stateEnum;

    public Deviceclass getDeviceClass() {
        return deviceClass;
    }

    public void setDeviceClass(Deviceclass deviceClass) {
        this.deviceClass = deviceClass;
    }
    public Partner getPartner() {
        return partner;
    }

    public void setPartner(Partner partner) {
        this.partner = partner;
    }

    public StateEnum getStateEnum() {
        return stateEnum;
    }

    public void setStateEnum(StateEnum stateEnum) {
        this.stateEnum = stateEnum;
    }
}
