package com.hy.common.model;

import com.hy.common.model.base.BaseDict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dict extends BaseDict<Dict> {
	
	    private Integer id ; //
	    private String pcode ; //
	    private String code ; //
	    private Integer pid ; //
	    private String name ; //
	    private String tips ; //
	    private Integer version ; //

}
