package com.hy.common.model;


import com.hy.common.model.base.BaseEngineerManage;

import java.util.Date;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EngineerManage extends BaseEngineerManage<EngineerManage> {

	private Integer id ; //
	private String taskName ; //
	private Integer taskType ; //
	private Date taskTime ; //
	private Integer userId ; //
	private String planNum ; //
	private String planBuget ; //
	private String require ; //
	private String planBook ; //
	private String tips ; //
	private String status ; //

}
