package com.hy.common.model;

import com.hy.common.model.base.BaseEnterstock;
import com.jfinal.plugin.activerecord.Record;

import java.util.List;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Enterstock extends BaseEnterstock<Enterstock> {

	private java.lang.Integer id ; //
	private java.lang.String enterStockId ; //
	private java.util.Date enterDate ; //
	private java.lang.String userId ; //
	private java.lang.Integer warehouseId ; //
	private java.lang.String source ; //
	private java.lang.Integer status ; //
	private java.lang.Integer invoicenum ; //
	private java.lang.String remak ; //
	private java.lang.Integer entertype ; //
	private java.lang.String agency ; //
	private java.lang.String sumMoney ; //
	private java.lang.String sumNum ; //
	private java.lang.String fileNumber ; //

	private List<Record> enterdetailList;

	public List<Record> getEnterdetailList() {
		return enterdetailList;
	}

	public void setEnterdetailList(List<Record> enterdetailList) {
		this.enterdetailList = enterdetailList;
	}
}
