package com.hy.common.model;

import com.hy.common.model.base.BaseInoutrecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Inoutrecord extends BaseInoutrecord<Inoutrecord> {
	
	    private Integer id ; //
	    private Integer number ; //
	    private Integer inOut ; //
	    private Integer type ; //
	    private String auditor ; //
	    private java.util.Date auditTime ; //
	    private String preparedMan ; //
	    private java.util.Date preparedTime ; //

}
