package com.hy.common.model;

import com.hy.common.model.base.BaseInstall;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Install extends BaseInstall<Install> {
	
	    private Integer id ; //
	    private String installId ; //
	    private String installMan ; //
	    private java.util.Date installTime ; //
	    private java.util.Date appearTime ; //

}
