package com.hy.common.model;

import com.hy.common.model.base.BaseLeavestock;
import com.jfinal.plugin.activerecord.Record;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LeaveStock extends BaseLeavestock<LeaveStock> {
	
	    private Integer id ; //
	    private String leavestockId ; //
		private String equipFile;//
	    private java.util.Date leavedate ; //
	    private Integer deptId ; //
	    private Integer enterStockId ; //
	    private Integer storehouseId ; //
	    private double sumMoney ; //
		private double sumNum ; //
	    private String userId ; //
	    private Integer status ; //
	    private Integer leaveType ; //
		private List<Record> leavedetailList;

	public List<Record> getLeavedetailList() {
		return leavedetailList;
	}

	public void setLeavedetailList(List<Record> leavedetailList) {
		this.leavedetailList = leavedetailList;
	}
}
