package com.hy.common.model;

import com.hy.common.model.base.BaseLeavestockDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LeaveStockDetail extends BaseLeavestockDetail<LeaveStockDetail> {
	
	    private Integer id ; //
	    private String fileNumber ; //
	    private Integer leaveId ; //
	    private String leaveDate ; //
	    private Integer leavenum ; //
	    private String deviceName ; //
	    private String deviceClassName ; //

}
