package com.hy.common.model;

import com.hy.common.model.base.BaseOperationLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OperationLog extends BaseOperationLog<OperationLog> {
    private Integer id ; //
    private String logName ; //
    private Integer userd ; //
    private String classname ; //
    private String method ; //
    private Integer version ; //
    private String succeed ; //
    private Integer message ; //
	
}
