package com.hy.common.model;

import com.hy.common.model.base.BaseParameter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Parameter extends BaseParameter<Parameter> {
	
	    private Integer id ; //
	    private String code ; //
	    private Integer num ; //
	    private String name ; //
	    private String para ; //
	    private String tips ; //
	    private Integer status ; //
	    private Integer version ; //

}
