package com.hy.common.model;

import com.hy.common.model.base.BasePartner;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Partner extends BasePartner<Partner> {
    private Integer id ; //
    private String companyName ; //
    private String account ; //
    private String nationality ; //
    private Integer type ; //
    private String brand ; //
    private String contact ; //
    private String contactTel ; //
    private String address;
    private Integer pid;

	
}
