package com.hy.common.model;

import com.hy.common.model.base.BasePlanTaskdetail;

import java.util.Date;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlanTaskdetail extends BasePlanTaskdetail<PlanTaskdetail> {

	private Integer id ; //
	private Integer applyId ; //
	private Integer taskId ; //

}
