package com.hy.common.model;

import com.hy.common.model.base.BaseApply;
import com.hy.common.model.base.BasePlanTask;
import com.jfinal.plugin.activerecord.Record;

import java.util.Date;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlanTask extends BasePlanTask<PlanTask> {

	    private Integer id ; //
	    private String taskName ; //
		private Integer taskType ; //
	    private Date taskTime ; //
	    private Integer userId ; //
	    private String planNum ; //
	    private String planBuget ; //
	    private String require ; //
	    private String planBook ; //
		private String tips ; //
	    private String status ; //
}
