package com.hy.common.model;


import com.hy.common.model.base.BasePurchaseTaskDetail;

import java.util.Date;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PurchaseTaskDetail extends BasePurchaseTaskDetail<PurchaseTaskDetail> {

	    private Integer id ; //
		private Integer taskNum ; //
		private Integer pursureId ; //
		private Integer num ; //
	    private String deviceName ; //
		private String unit ; //
	    private String buget ; //
		private String source ; //
		private Integer userId ; //
		private String parameters ; //
}
