package com.hy.common.model;

import com.hy.common.model.base.BasePurchaseTask;

import java.util.Date;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PurchaseTask extends BasePurchaseTask<PurchaseTask> {

	    private Integer id ; //
	    private String taskName ; //
		private String taskType ; //
	    private Date time ; //
	    private Integer userId ; //
	    private String taskNum ; //
	    private String sumBuget ; //
		private Integer planId ; //
}
