package com.hy.common.model;

import com.hy.common.model.base.BaseRoles;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Roles extends BaseRoles<Roles> {
	
	    private Integer id ; //
	    private Integer num ; //
	    private Integer pid ; //
	    private String name ; //
	    private Integer deptId ; //
	    private String tips ; //
	    private Integer version ; //

}
