package com.hy.common.model;

import com.hy.common.model.base.BaseStockpilesubinfor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Stockpilesubinfor extends BaseStockpilesubinfor<Stockpilesubinfor> {
	
	    private Integer id ; //
	    private Integer stockpileId ; //
	    private Integer deptStockId ; //
	    private Integer propertyId ; //
	    private String fixedAssets ; //
	    private Integer facNumber ; //
	    private Integer companyId ; //
	    private java.util.Date productDate ; //
	    private java.util.Date acceptanceDate ; //
	    private java.util.Date buyDate ; //
	    private Integer regisNumber ; //
	    private String riskAssets ; //
	    private String emergencyDevice ; //
	    private String specialDevice ; //
	    private Integer mainPeriod ; //
	    private Integer meaPeriod ; //
	    private Integer quaPeriod ; //
	    private String  DepreWay ; //
		private String deviceType;//
}
