package com.hy.common.model;

import com.hy.common.model.base.BaseStockStockpile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StockStockpile extends BaseStockStockpile<StockStockpile> {
	
	    private Integer id ; //
	    private Integer storehouseId ; //
	    private Integer deviceId ; //
	    private java.util.Date firstEnterDate ; //
	    private java.util.Date lastLeaveDate ; //
	    private Integer number ; //
	    private Double price ; //
	    private String code ; //
	    private String fileNumber ; //
	    private Integer classId ; //
	    private String brand ; //
	    private Integer enterId ; //
	    private Integer warehouseId ; //
	    private Integer companyId ; //

}
