package com.hy.common.model;

import com.hy.common.model.base.BaseUpkeep;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Upkeep extends BaseUpkeep<Upkeep> {
	
	    private Integer id ; //
	    private String upkeepType ; //
	    private String upkeeper ; //
	    private Integer status ; //
	    private java.util.Date date ; //
	    private java.util.Date time ; //

}
