package com.hy.common.model;

import com.hy.common.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {

    private java.lang.Integer id ; //
    private java.lang.String account ; //
    private java.lang.String password ; //
    private java.lang.String salt ; //
    private java.lang.String name ; //
    private java.util.Date birthday ; //
    private java.lang.Integer sex ; //
    private java.lang.String email ; //
    private java.lang.String phone ; //
    private java.lang.String roleId ; //
    private java.lang.Integer positionId ; //
    private java.lang.Integer deptId ; //
    private java.lang.Integer status ; //
    private java.util.Date createtime ; //
    private java.lang.Integer version ; //

}
