package com.hy.common.model;

import com.hy.common.model.base.BaseWarehouse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Warehouse extends BaseWarehouse<Warehouse> {
	
	    private Integer id ; //
	    private String type ; //
	    private String name ; //
	    private String remark ; //
		private Integer pid ; //

}
