package com.hy.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseApplyinfor<M extends BaseApplyinfor<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setApplyId(java.lang.Integer applyId) {
		set("applyId", applyId);
	}
	
	public java.lang.Integer getApplyId() {
		return getInt("applyId");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setFileName(java.lang.String fileName) {
		set("fileName", fileName);
	}
	
	public java.lang.String getFileName() {
		return getStr("fileName");
	}

	public void setPath(java.lang.String path) {
		set("path", path);
	}
	
	public java.lang.String getPath() {
		return getStr("path");
	}

}
