package com.hy.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDeptstock<M extends BaseDeptstock<M>> extends Model<M> implements IBean {
	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getInt("id");
	}

	public void setFileNumber(String fileNumber) {
		set("fileNumber", fileNumber);
	}

	public String getFileNumber() {
		return getStr("fileNumber");
	}

	public void setDeptId(Integer deptId) {
		set("deptId", deptId);
	}

	public Integer getDeptId() {
		return getInt("deptId");
	}

	public void setStorehouseId(Integer storehouseId) {
		set("storehouseId", storehouseId);
	}

	public Integer getStorehouseId() {
		return getInt("storehouseId");
	}

	public void setDeviceId(Integer deviceId) {
		set("deviceId", deviceId);
	}

	public Integer getDeviceId() {
		return getInt("deviceId");
	}

	public void setEnterDate(java.util.Date enterDate) {
		set("enterDate", enterDate);
	}

	public java.util.Date getEnterDate() {
		return get("enterDate");
	}

	public void setNumber(Integer number) {
		set("number", number);
	}

	public Integer getNumber() {
		return getInt("number");
	}

	public void setPrice(Double price) {
		set("price", price);
	}

	public Double getPrice() {
		return getDouble("price");
	}

	public void setProductDate(java.util.Date productDate) {
		set("productDate", productDate);
	}

	public java.util.Date getProductDate() {
		return get("productDate");
	}

	public void setUseTime(Integer useTime) {
		set("useTime", useTime);
	}

	public Integer getUseTime() {
		return getInt("useTime");
	}

	public void setBathnum(Integer bathnum) {
		set("bathnum", bathnum);
	}

	public Integer getBathnum() {
		return getInt("bathnum");
	}

	public void setPropertyId(Integer propertyId) {
		set("propertyId", propertyId);
	}

	public Integer getPropertyId() {
		return getInt("propertyId");
	}

	public void setCode(String code) {
		set("code", code);
	}

	public String getCode() {
		return getStr("code");
	}

	public void setPeriod(String period) {
		set("period", period);
	}

	public String getPeriod() {
		return getStr("period");
	}

	public void setStockId(Integer stockId) {
		set("stockId", stockId);
	}

	public Integer getStockId() {
		return getInt("stockId");
	}

	public void setDeviceName(String deviceName) {
		set("deviceName", deviceName);
	}

	public String getDeviceName() {
		return getStr("deviceName");
	}

	public void setDeviceClassName(String deviceClassName) {
		set("deviceClassName", deviceClassName);
	}

	public String getDeviceClassName() {
		return getStr("deviceClassName");
	}

}
