package com.hy.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDict<M extends BaseDict<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setPcode(java.lang.String pcode) {
		set("pcode", pcode);
	}
	
	public java.lang.String getPcode() {
		return getStr("pcode");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}

	public void setPid(java.lang.Integer pid) {
		set("pid", pid);
	}
	
	public java.lang.Integer getPid() {
		return getInt("pid");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setTips(java.lang.String tips) {
		set("tips", tips);
	}
	
	public java.lang.String getTips() {
		return getStr("tips");
	}

	public void setVersion(java.lang.Integer version) {
		set("version", version);
	}
	
	public java.lang.Integer getVersion() {
		return getInt("version");
	}

}
