package com.hy.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStockpilesubinfor<M extends BaseStockpilesubinfor<M>> extends Model<M> implements IBean {
	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getInt("id");
	}

	public void setStockpileId(Integer stockpileId) {
		set("stockpileId", stockpileId);
	}

	public Integer getStockpileId() {
		return getInt("stockpileId");
	}

	public void setDeptStockId(Integer deptStockId) {
		set("deptStockId", deptStockId);
	}

	public Integer getDeptStockId() {
		return getInt("deptStockId");
	}

	public void setPropertyId(Integer propertyId) {
		set("propertyId", propertyId);
	}

	public Integer getPropertyId() {
		return getInt("propertyId");
	}

	public void setFixedAssets(String fixedAssets) {
		set("fixedAssets", fixedAssets);
	}

	public String getFixedAssets() {
		return getStr("fixedAssets");
	}

	public void setFacNumber(Integer facNumber) {
		set("facNumber", facNumber);
	}

	public Integer getFacNumber() {
		return getInt("facNumber");
	}

	public void setCompanyId(Integer companyId) {
		set("companyId", companyId);
	}

	public Integer getCompanyId() {
		return getInt("companyId");
	}

	public void setProductDate(java.util.Date productDate) {
		set("productDate", productDate);
	}

	public java.util.Date getProductDate() {
		return get("productDate");
	}

	public void setAcceptanceDate(java.util.Date acceptanceDate) {
		set("acceptanceDate", acceptanceDate);
	}

	public java.util.Date getAcceptanceDate() {
		return get("acceptanceDate");
	}

	public void setBuyDate(java.util.Date buyDate) {
		set("buyDate", buyDate);
	}

	public java.util.Date getBuyDate() {
		return get("buyDate");
	}

	public void setRegisNumber(Integer regisNumber) {
		set("regisNumber", regisNumber);
	}

	public Integer getRegisNumber() {
		return getInt("regisNumber");
	}

	public void setRiskAssets(String riskAssets) {
		set("riskAssets", riskAssets);
	}

	public String getRiskAssets() {
		return getStr("riskAssets");
	}

	public void setEmergencyDevice(String emergencyDevice) {
		set("emergencyDevice", emergencyDevice);
	}

	public String getEmergencyDevice() {
		return getStr("emergencyDevice");
	}

	public void setSpecialDevice(String specialDevice) {
		set("specialDevice", specialDevice);
	}

	public String getSpecialDevice() {
		return getStr("specialDevice");
	}

	public void setMainPeriod(Integer mainPeriod) {
		set("mainPeriod", mainPeriod);
	}

	public Integer getMainPeriod() {
		return getInt("mainPeriod");
	}

	public void setMeaPeriod(Integer meaPeriod) {
		set("meaPeriod", meaPeriod);
	}

	public Integer getMeaPeriod() {
		return getInt("meaPeriod");
	}

	public void setQuaPeriod(Integer quaPeriod) {
		set("quaPeriod", quaPeriod);
	}

	public Integer getQuaPeriod() {
		return getInt("quaPeriod");
	}

	public void setDepreWay(String DepreWay) {
		set("DepreWay", DepreWay);
	}

	public String getDepreWay() {
		return getStr("DepreWay");
	}

	public void setDeviceType(String deviceType) {
		set("deviceType", deviceType);
	}

	public String getDeviceType() {
		return getStr("deviceType");
	}

}
