package com.hy.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseApply<M extends BaseApply<M>> extends Model<M> implements IBean{

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getInt("id");
	}

	public void setPlanType(String planType) {
		set("planType", planType);
	}

	public String getPlanType() {
		return getStr("planType");
	}

	public void setPlanName(String planName) {
		set("planName", planName);
	}

	public String getPlanName() {
		return getStr("planName");
	}

	public void setCode(String Code) {
		set("Code", Code);
	}

	public String getCode() {
		return getStr("Code");
	}

	public void setDeptId(Integer deptId) {
		set("deptId", deptId);
	}

	public Integer getDeptId() {
		return getInt("deptId");
	}

	public void setUserId(Integer userId) {
		set("userId", userId);
	}

	public Integer getUserId() {
		return getInt("userId");
	}

	public void setDeviceNumber(String deviceNumber) {
		set("deviceNumber", deviceNumber);
	}

	public String getDeviceNumber() {
		return getStr("deviceNumber");
	}

	public void setUnit(String unit) {
		set("unit", unit);
	}

	public String getUnit() {
		return getStr("unit");
	}

	public void setDeviceId(String deviceId) {
		set("deviceId", deviceId);
	}

	public String getDeviceId() {
		return getStr("deviceId");
	}

	public void setPurchaseDate(java.util.Date purchaseDate) {
		set("purchaseDate", purchaseDate);
	}

	public java.util.Date getPurchaseDate() {
		return get("purchaseDate");
	}

	public void setBudget(Double budget) {
		set("budget", budget);
	}

	public Double getBudget() {
		return getDouble("budget");
	}

	public void setCapitalSource(String capitalSource) {
		set("capitalSource", capitalSource);
	}

	public String getCapitalSource() {
		return getStr("capitalSource");
	}

	public void setApplyReason(String applyReason) {
		set("applyReason", applyReason);
	}

	public String getApplyReason() {
		return getStr("applyReason");
	}

	public void setUserDept(String userDept) {
		set("userDept", userDept);
	}

	public String getUserDept() {
		return getStr("userDept");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setStatus(String status) {
		set("status", status);
	}

	public String getStatus() {
		return getStr("status");
	}

	public void setAuditor(Integer auditor) {
		set("auditor", auditor);
	}

	public Integer getAuditor() {
		return getInt("auditor");
	}

	public void setAuditOpinion(String auditOpinion) {
		set("auditOpinion", auditOpinion);
	}

	public String getAuditOpinion() {
		return getStr("auditOpinion");
	}

	public void setAuditTime(java.util.Date auditTime) {
		set("auditTime", auditTime);
	}
	
	public java.util.Date getAuditTime() {
		return get("auditTime");
	}

	public String getEnName() {
		return get("enName");
	}

	public void setEnName(String enName) {
		set("enName", enName);
	}

	public String getCnName() {
		return get("cnName");
	}

	public void setCnName(String cnName) {
		set("cnName", cnName);
	}
}
