package com.hy.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSubservice<M extends BaseSubservice<M>> extends Model<M> implements IBean {
	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getInt("id");
	}

	public void setCompanyId(Integer companyId) {
		set("companyId", companyId);
	}

	public Integer getCompanyId() {
		return getInt("companyId");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return getInt("status");
	}

	public void setDate(java.util.Date date) {
		set("date", date);
	}

	public java.util.Date getDate() {
		return get("date");
	}

	public void setType(String type) {
		set("type", type);
	}

	public String getType() {
		return getStr("type");
	}

	public void setPhone(Integer phone) {
		set("phone", phone);
	}

	public Integer getPhone() {
		return getInt("phone");
	}

	public void setFileId(Integer fileId) {
		set("fileId", fileId);
	}

	public Integer getFileId() {
		return getInt("fileId");
	}

	public void setRemark(String remark) {
		set("remark", remark);
	}

	public String getRemark() {
		return getStr("remark");
	}

}
