package com.hy.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

import java.util.Date;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlanTaskdetail<M extends BasePlanTaskdetail<M>> extends Model<M> implements IBean {
	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getInt("id");
	}

	public void setApplyId(Integer applyId) {
		set("applyId", applyId);
	}

	public Integer getApplyId() {
		return getInt("applyId");
	}

	public void setTaskId(Integer taskId) {
		set("taskId", taskId);
	}

	public Integer getTaskId() {
		return getInt("taskId");
	}
}
