package com.hy.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMenu<M extends BaseMenu<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}

	public void setPcode(java.lang.String pcode) {
		set("pcode", pcode);
	}
	
	public java.lang.String getPcode() {
		return getStr("pcode");
	}

	public void setAlias(java.lang.String alias) {
		set("alias", alias);
	}
	
	public java.lang.String getAlias() {
		return getStr("alias");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setIcon(java.lang.String icon) {
		set("icon", icon);
	}
	
	public java.lang.String getIcon() {
		return getStr("icon");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

	public void setNum(java.lang.Integer num) {
		set("num", num);
	}
	
	public java.lang.Integer getNum() {
		return getInt("num");
	}

	public void setLevels(java.lang.Integer levels) {
		set("levels", levels);
	}
	
	public java.lang.Integer getLevels() {
		return getInt("levels");
	}

	public void setMenuType(java.lang.Integer menuType) {
		set("menuType", menuType);
	}
	
	public java.lang.Integer getMenuType() {
		return getInt("menuType");
	}

	public void setPath(java.lang.String path) {
		set("path", path);
	}
	
	public java.lang.String getPath() {
		return getStr("path");
	}

	public void setTips(java.lang.String tips) {
		set("tips", tips);
	}
	
	public java.lang.String getTips() {
		return getStr("tips");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setIsopen(java.lang.String isopen) {
		set("isopen", isopen);
	}
	
	public java.lang.String getIsopen() {
		return getStr("isopen");
	}

	public void setIstemplate(java.lang.String istemplate) {
		set("istemplate", istemplate);
	}
	
	public java.lang.String getIstemplate() {
		return getStr("istemplate");
	}

	public void setVersion(java.lang.Integer version) {
		set("version", version);
	}
	
	public java.lang.Integer getVersion() {
		return getInt("version");
	}

}
