package com.hy.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAllot<M extends BaseAllot<M>> extends Model<M> implements IBean {
	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getInt("id");
	}

	public void setAllotId(Integer allotId) {
		set("allotId", allotId);
	}

	public Integer getAllotId() {
		return getInt("allotId");
	}

	public void setAllotType(String allotType) {
		set("allotType", allotType);
	}

	public String getAllotType() {
		return getStr("allotType");
	}

	public void setFromStock(String fromStock) {
		set("fromStock", fromStock);
	}

	public String getFromStock() {
		return getStr("fromStock");
	}

	public void setToStock(String toStock) {
		set("toStock", toStock);
	}

	public String getToStock() {
		return getStr("toStock");
	}

	public void setNum(Integer num) {
		set("num", num);
	}

	public Integer getNum() {
		return getInt("num");
	}

	public void setPrice(Double price) {
		set("price", price);
	}

	public Double getPrice() {
		return getDouble("price");
	}

	public void setUserId(Integer userId) {
		set("userId", userId);
	}

	public Integer getUserId() {
		return getInt("userId");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

}
