package com.hy.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStockStockpile<M extends BaseStockStockpile<M>> extends Model<M> implements IBean {
	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getInt("id");
	}

	public void setStorehouseId(Integer storehouseId) {
		set("storehouseId", storehouseId);
	}

	public Integer getStorehouseId() {
		return getInt("storehouseId");
	}

	public void setDeviceId(Integer deviceId) {
		set("deviceId", deviceId);
	}

	public Integer getDeviceId() {
		return getInt("deviceId");
	}

	public void setFirstEnterDate(java.util.Date firstEnterDate) {
		set("firstEnterDate", firstEnterDate);
	}

	public java.util.Date getFirstEnterDate() {
		return get("firstEnterDate");
	}

	public void setLastLeaveDate(java.util.Date lastLeaveDate) {
		set("lastLeaveDate", lastLeaveDate);
	}

	public java.util.Date getLastLeaveDate() {
		return get("lastLeaveDate");
	}

	public void setNumber(Integer number) {
		set("number", number);
	}

	public Integer getNumber() {
		return getInt("number");
	}

	public void setPrice(Double price) {
		set("price", price);
	}

	public Double getPrice() {
		return getDouble("price");
	}

	public void setCode(String code) {
		set("code", code);
	}

	public String getCode() {
		return getStr("code");
	}

	public void setFileNumber(String fileNumber) {
		set("fileNumber", fileNumber);
	}

	public String getFileNumber() {
		return getStr("fileNumber");
	}

	public void setClassId(Integer classId) {
		set("classId", classId);
	}

	public Integer getClassId() {
		return getInt("classId");
	}

	public void setBrand(String brand) {
		set("brand", brand);
	}

	public String getBrand() {
		return getStr("brand");
	}

	public void setEnterId(Integer enterId) {
		set("enterId", enterId);
	}

	public Integer getEnterId() {
		return getInt("enterId");
	}

	public void setWarehouseId(Integer warehouseId) {
		set("warehouseId", warehouseId);
	}

	public Integer getWarehouseId() {
		return getInt("warehouseId");
	}

	public void setCompanyId(Integer companyId) {
		set("companyId", companyId);
	}

	public Integer getCompanyId() {
		return getInt("companyId");
	}

}
