package com.hy.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseServicerecord<M extends BaseServicerecord<M>> extends Model<M> implements IBean {
	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getInt("id");
	}

	public void setFinTime(java.util.Date finTime) {
		set("finTime", finTime);
	}

	public java.util.Date getFinTime() {
		return get("finTime");
	}

	public void setServiceType(String serviceType) {
		set("serviceType", serviceType);
	}

	public String geServiceType() {
		return getStr("serviceType");
	}

	public void setMoney(Integer money) {
		set("money", money);
	}

	public Integer getMoney() {
		return getInt("money");
	}

	public void setTips(String tips) {
		set("tips", tips);
	}

	public String getTips() {
		return getStr("tips");
	}

}
