package com.hy.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUpkeep<M extends BaseUpkeep<M>> extends Model<M> implements IBean {
	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getInt("id");
	}

	public void setUpkeepType(String upkeepType) {
		set("upkeepType", upkeepType);
	}

	public String getUpkeepType() {
		return getStr("upkeepType");
	}

	public void setUpkeeper(String upkeeper) {
		set("upkeeper", upkeeper);
	}

	public String getUpkeeper() {
		return getStr("upkeeper");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return getInt("status");
	}

	public void setDate(java.util.Date date) {
		set("date", date);
	}
	
	public java.util.Date getDate() {
		return get("date");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

}
