package com.hy.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

import java.util.Date;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePurchaseTask<M extends BasePurchaseTask<M>> extends Model<M> implements IBean {
	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getInt("id");
	}

	public void setTaskName(String taskName) {
		set("taskName", taskName);
	}

	public String getTaskName() {
		return getStr("taskName");
	}

	public void setTaskType(int taskType) {
		set("taskType", taskType);
	}

	public String getTaskType() {
		return getStr("taskType");
	}

	public void setTime(Date time) {
		set("time", time);
	}

	public Date getTime() {
		return getDate("time");
	}

	public void setUserId(int userId) {
		set("userId", userId);
	}

	public int getUserId() {
		return getInt("userId");
	}

	public void setTaskNum(String taskNum) {
		set("taskNum", taskNum);
	}

	public String getTaskNum() {
		return getStr("taskNum");
	}

	public void setSumBuget(String sumBuget) {
		set("sumBuget", sumBuget);
	}

	public String getSumBuget() {
		return getStr("sumBuget");
	}

	public void setPlanId(Integer planId) {
		set("planId", planId);
	}

	public Integer getPlanId() {
		return getInt("planId");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return getInt("status");
	}
}
