package com.hy.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLeavestock<M extends BaseLeavestock<M>> extends Model<M> implements IBean {
	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getInt("id");
	}

	public void setLeavestockId(String leavestockId) {
		set("leavestockId", leavestockId);
	}

	public String getLeavestockId() {
		return getStr("leavestockId");
	}

	public void setgetEquipFile(String equipFile) {
		set("equipFile", equipFile);
	}

	public String getEquipFile() {
		return getStr("equipFile");
	}

	public void setLeavedate(java.util.Date leavedate) {
		set("leavedate", leavedate);
	}

	public java.util.Date getLeavedate() {
		return get("leavedate");
	}

	public void setDeptId(Integer deptId) {
		set("deptId", deptId);
	}

	public Integer getDeptId() {
		return getInt("deptId");
	}

	public void setEnterStockId(Integer enterStockId) {
		set("enterStockId", enterStockId);
	}

	public Integer getEnterStockId() {
		return getInt("enterStockId");
	}

	public void setStorehouseId(Integer storehouseId) {
		set("storehouseId", storehouseId);
	}

	public Integer getStorehouseId() {
		return getInt("storehouseId");
	}

	public void setSumNum(double sumNum) {
		set("sumNum", sumNum);
	}

	public double getSumNum() {
		return getDouble("sumNum");
	}

	public void setSumMoney(double sumMoney) {
		set("sumMoney", sumMoney);
	}

	public double getSumMoney() {
		return getDouble("sumMoney");
	}

	public void setUserId(String userId) {
		set("userId", userId);
	}

	public String getUserId() {
		return getStr("userId");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return getInt("status");
	}

	public void setLeaveType(Integer leaveType) {
		set("leaveType", leaveType);
	}

	public Integer getLeaveType() {
		return getInt("leaveType");
	}

}
