package com.hy.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePartner<M extends BasePartner<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setPid(java.lang.Integer pid) {
		set("pid", pid);
	}

	public java.lang.Integer getPid() {
		return getInt("pid");
	}

	public void setCompanyName(java.lang.String companyName) {
		set("companyName", companyName);
	}
	
	public java.lang.String getCompanyName() {
		return getStr("companyName");
	}

	public void setAccount(java.lang.String account) {
		set("account", account);
	}
	
	public java.lang.String getAccount() {
		return getStr("account");
	}

	public void setNationality(java.lang.String nationality) {
		set("nationality", nationality);
	}
	
	public java.lang.String getNationality() {
		return getStr("nationality");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setBrand(java.lang.String brand) {
		set("brand", brand);
	}
	
	public java.lang.String getBrand() {
		return getStr("brand");
	}

	public void setContact(java.lang.String contact) {
		set("contact", contact);
	}

	public java.lang.String getContact() {
		return getStr("contact");
	}
	public void setContactTel(java.lang.String contactTel) {
		set("contactTel", contactTel);
	}

	public java.lang.String getContactTel() {
		return getStr("contactTel");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return getStr("address");
	}

}
