package com.hy.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

import java.util.Date;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStockpile<M extends BaseStockpile<M>> extends Model<M> implements IBean {
	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getInt("id");
	}

	public void setStorehouseId(Integer storehouseId) {
		set("storehouseId", storehouseId);
	}

	public Integer getStorehouseId() {
		return getInt("storehouseId");
	}

	public void setDeviceId(Integer deviceId) {
		set("deviceId", deviceId);
	}

	public Integer getDeviceId() {
		return getInt("deviceId");
	}

	public void setFirstEnterDate(Date firstEnterDate) {
		set("firstEnterDate", firstEnterDate);
	}

	public Date getFirstEnterDate() {
		return getDate("firstEnterDate");
	}

	public void setLastLeaveDate(Date lastLeaveDate) {
		set("lastLeaveDate", lastLeaveDate);
	}

	public Date getLastLeaveDate() {
		return getDate("lastLeaveDate");
	}

	public void setNumber(String number) {
		set("number", number);
	}

	public String getNumber() {
		return getStr("number");
	}

	public void setPrice(Double price) {
		set("price", price);
	}

	public Double getPrice() {
		return getDouble("price");
	}

	public void setCode(String code) {
		set("code", code);
	}

	public String getCode() {
		return getStr("code");
	}

	public void setFileNumber(String fileNumber) {
		set("fileNumber", fileNumber);
	}

	public String getFileNumber() {
		return getStr("fileNumber");
	}

	public void setClassId(Integer classId) {
		set("classId", classId);
	}

	public Integer getClassId() {
		return getInt("classId");
	}

	public void setBrand(String brand) {
		set("brand", brand);
	}

	public String getBrand() {
		return getStr("brand");
	}

	public void setEnterId(Integer enterId) {
		set("enterId", enterId);
	}

	public Integer getEnterId() {
		return getInt("enterId");
	}

	public void setWarehouseId(Integer warehouseId) {
		set("warehouseId", warehouseId);
	}

	public Integer getWarehouseId() {
		return getInt("warehouseId");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return getInt("status");
	}

	public void setSalvage(Integer salvage) {
		set("salvage", salvage);
	}

	public Integer getSalvage() {
		return getInt("salvage");
	}

	public void setScrap(Integer scrap) {
		set("scrap", scrap);
	}

	public Integer getScrap() {
		return getInt("scrap");
	}

	public void setDeptId(Integer deptId) {
		set("deptId", deptId);
	}

	public Integer getDeptId() {
		return getInt("deptId");
	}

	public void setUserId(Integer userId) {
		set("userId", userId);
	}

	public Integer getUserId() {
		return getInt("userId");
	}
}
