package com.hy.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAllotDetail<M extends BaseAllotDetail<M>> extends Model<M> implements IBean {
	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getInt("id");
	}

	public void setPlace(String place) {
		set("place", place);
	}

	public String getPlace() {
		return getStr("place");
	}

	public void setFileNumber(Integer fileNumber) {
		set("fileNumber", fileNumber);
	}

	public Integer getFileNumber() {
		return getInt("fileNumber");
	}

	public void setDeviceName(String deviceName) {
		set("deviceName", deviceName);
	}

	public String getDeviceName() {
		return getStr("deviceName");
	}

	public void setModle(String modle) {
		set("modle", modle);
	}

	public String getModle() {
		return getStr("modle");
	}

	public void setPrice(Double price) {
		set("price", price);
	}

	public Double getPrice() {
		return getDouble("price");
	}

	public void setAgency(String agency) {
		set("agency", agency);
	}

	public String getAgency() {
		return getStr("agency");
	}

	public void setCompany(String company) {
		set("company", company);
	}

	public String getCompany() {
		return getStr("company");
	}

	public void setBrund(String brund) {
		set("brund", brund);
	}

	public String getBrund() {
		return getStr("brund");
	}

}
