package com.hy.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

import java.util.Date;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseInstallManage<M extends BaseInstallManage<M>> extends Model<M> implements IBean {
	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getInt("id");
	}

	public void setTaskName(String taskName) {
		set("taskName", taskName);
	}

	public String getTaskName() {
		return getStr("taskName");
	}

	public void setTaskType(int taskType) {
		set("taskType", taskType);
	}

	public int getTaskType() {
		return getInt("taskType");
	}

	public void setTaskTime(Date taskTime) {
		set("taskTime", taskTime);
	}

	public Date getTaskTime() {
		return getDate("taskTime");
	}

	public void setUserId(int userId) {
		set("userId", userId);
	}

	public int getUserId() {
		return getInt("userId");
	}

	public void setPlanNum(String planNum) {
		set("planNum", planNum);
	}

	public String getPlanNum() {
		return getStr("planNum");
	}

	public void setPlanBuget(String planBuget) {
		set("planBuget", planBuget);
	}

	public String getPlanBuget() {
		return getStr("planBuget");
	}

	public void setRequire(String require) {
		set("require", require);
	}

	public String getRequire() {
		return getStr("require");
	}

	public void setPlanBook(String planBook) {
		set("planBook", planBook);
	}

	public String getPlanBook() {
		return getStr("planBook");
	}

	public void setTips(String tips) {
		set("tips", tips);
	}

	public String getTips() {
		return getStr("tips");
	}

	public void setStatus(String status) {
		set("status", status);
	}

	public String getStatus() {
		return getStr("status");
	}

}
