package com.hy.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEnterstock<M extends BaseEnterstock<M>> extends Model<M> implements IBean {
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return getStr("id");
	}

	public void setEnterStockId(java.lang.String enterStockId) {
		set("enterStockId", enterStockId);
	}

	public java.lang.String getEnterStockId() {
		return getStr("enterStockId");
	}

	public void setEnterDate(java.util.Date enterDate) {
		set("enterDate", enterDate);
	}

	public java.util.Date getEnterDate() {
		return get("enterDate");
	}

	public void setUserId(java.lang.String userId) {
		set("userId", userId);
	}

	public java.lang.String getUserId() {
		return getStr("userId");
	}

	public void setWarehouseId(java.lang.Integer warehouseId) {
		set("warehouseId", warehouseId);
	}

	public java.lang.Integer getWarehouseId() {
		return getInt("warehouseId");
	}

	public void setSource(java.lang.String source) {
		set("source", source);
	}

	public java.lang.String getSource() {
		return getStr("source");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setInvoicenum(java.lang.Integer invoicenum) {
		set("invoicenum", invoicenum);
	}

	public java.lang.Integer getInvoicenum() {
		return getInt("invoicenum");
	}

	public void setRemak(java.lang.String remak) {
		set("remak", remak);
	}

	public java.lang.String getRemak() {
		return getStr("remak");
	}

	public void setEntertype(java.lang.Integer entertype) {
		set("entertype", entertype);
	}

	public java.lang.Integer getEntertype() {
		return getInt("entertype");
	}

	public void setAgency(java.lang.String agency) {
		set("agency", agency);
	}

	public java.lang.String getAgency() {
		return getStr("agency");
	}

	public void setSumMoney(java.lang.String sumMoney) {
		set("sumMoney", sumMoney);
	}

	public java.lang.String getSumMoney() {
		return getStr("sumMoney");
	}

	public void setSumNum(java.lang.String sumNum) {
		set("sumNum", sumNum);
	}

	public java.lang.String getSumNum() {
		return getStr("sumNum");
	}

	public void setFileNumber(java.lang.String fileNumber) {
		set("fileNumber", fileNumber);
	}

	public java.lang.String getFileNumber() {
		return getStr("fileNumber");
	}

}
