package com.hy.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseApplybenefit<M extends BaseApplybenefit<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setApplyId(java.lang.Integer applyId) {
		set("applyId", applyId);
	}
	
	public java.lang.Integer getApplyId() {
		return getInt("applyId");
	}

	public void setUseYear(java.lang.String useYear) {
		set("useYear", useYear);
	}
	
	public java.lang.String getUseYear() {
		return getStr("useYear");
	}

	public void setUseWeek(java.lang.String useWeek) {
		set("useWeek", useWeek);
	}
	
	public java.lang.String getUseWeek() {
		return getStr("useWeek");
	}

	public void setCharge(java.lang.String charge) {
		set("charge", charge);
	}
	
	public java.lang.String getCharge() {
		return getStr("charge");
	}

	public void setIncome(java.lang.String income) {
		set("income", income);
	}
	
	public java.lang.String getIncome() {
		return getStr("income");
	}

	public void setCost(java.lang.String cost) {
		set("cost", cost);
	}
	
	public java.lang.String getCost() {
		return getStr("cost");
	}

	public void setRecoveryTime(java.lang.String recoveryTime) {
		set("recoveryTime", recoveryTime);
	}
	
	public java.lang.String getRecoveryTime() {
		return getStr("recoveryTime");
	}

	public void setSampleNumber(java.lang.String sampleNumber) {
		set("sampleNumber", sampleNumber);
	}
	
	public java.lang.String getSampleNumber() {
		return getStr("sampleNumber");
	}

	public void setPeopleTimes(java.lang.String peopleTimes) {
		set("peopleTimes", peopleTimes);
	}
	
	public java.lang.String getPeopleTimes() {
		return getStr("peopleTimes");
	}

}
