package com.hy.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseInoutrecord<M extends BaseInoutrecord<M>> extends Model<M> implements IBean {
	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getInt("id");
	}

	public void setNumber(Integer number) {
		set("number", number);
	}

	public Integer getNumber() {
		return getInt("number");
	}

	public void setInOut(Integer inOut) {
		set("inOut", inOut);
	}

	public Integer getInOut() {
		return getInt("inOut");
	}

	public void setType(Integer type) {
		set("type", type);
	}

	public Integer getType() {
		return getInt("type");
	}

	public void setAuditor(String auditor) {
		set("auditor", auditor);
	}

	public String getAuditor() {
		return getStr("auditor");
	}

	public void setAuditTime(java.util.Date auditTime) {
		set("auditTime", auditTime);
	}

	public java.util.Date getAuditTime() {
		return get("auditTime");
	}

	public void setPreparedMan(String preparedMan) {
		set("preparedMan", preparedMan);
	}

	public String getPreparedMan() {
		return getStr("preparedMan");
	}

	public void setPreparedTime(java.util.Date preparedTime) {
		set("preparedTime", preparedTime);
	}
	
	public java.util.Date getPreparedTime() {
		return get("preparedTime");
	}

}
