package com.hy.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEnterstockDetail<M extends BaseEnterstockDetail<M>> extends Model<M> implements IBean {
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setDeviceId(java.lang.Integer deviceId) {
		set("deviceId", deviceId);
	}

	public java.lang.Integer getDeviceId() {
		return getInt("deviceId");
	}

	public void setEnternum(java.lang.String enternum) {
		set("enternum", enternum);
	}

	public java.lang.String getEnternum() {
		return getStr("enternum");
	}

	public void setPrice(java.lang.Double price) {
		set("price", price);
	}

	public java.lang.Double getPrice() {
		return getDouble("price");
	}

	public void setProductdate(java.util.Date productdate) {
		set("productdate", productdate);
	}

	public java.util.Date getProductdate() {
		return get("productdate");
	}

	public void setBeginTime(java.util.Date beginTime) {
		set("beginTime", beginTime);
	}

	public java.util.Date getBeginTime() {
		return get("beginTime");
	}

	public void setWarrantyPeriod(java.lang.Integer warrantyPeriod) {
		set("warrantyPeriod", warrantyPeriod);
	}

	public java.lang.Integer getWarrantyPeriod() {
		return getInt("warrantyPeriod");
	}

	public void setEnterId(java.lang.Integer enterId) {
		set("enterId", enterId);
	}

	public java.lang.Integer getEnterId() {
		return getInt("enterId");
	}

	public void setWareHouseId(java.lang.Integer wareHouseId) {
		set("wareHouseId", wareHouseId);
	}

	public java.lang.Integer getWareHouseId() {
		return getInt("wareHouseId");
	}

	public void setEnterType(java.lang.String enterType) {
		set("enterType", enterType);
	}

	public java.lang.String getEnterType() {
		return getStr("enterType");
	}

	public void setClassId(java.lang.Integer classId) {
		set("classId", classId);
	}

	public java.lang.Integer getClassId() {
		return getInt("classId");
	}

	public void setCompanyId(java.lang.Integer companyId) {
		set("companyId", companyId);
	}

	public java.lang.Integer getCompanyId() {
		return getInt("companyId");
	}

}
