package com.hy.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDept<M extends BaseDept<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setNum(java.lang.Integer num) {
		set("num", num);
	}
	
	public java.lang.Integer getNum() {
		return getInt("num");
	}

	public void setPid(java.lang.Integer pid) {
		set("pid", pid);
	}
	
	public java.lang.Integer getPid() {
		return getInt("pid");
	}

	public void setSimpleName(java.lang.String simpleName) {
		set("simpleName", simpleName);
	}
	
	public java.lang.String getSimpleName() {
		return getStr("simpleName");
	}

	public void setFullName(java.lang.String fullName) {
		set("fullName", fullName);
	}
	
	public java.lang.String getFullName() {
		return getStr("fullName");
	}

	public void setTips(java.lang.String tips) {
		set("tips", tips);
	}
	
	public java.lang.String getTips() {
		return getStr("tips");
	}

	public void setVersion(java.lang.Integer version) {
		set("version", version);
	}
	
	public java.lang.Integer getVersion() {
		return getInt("version");
	}

}
