package com.hy.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRepair<M extends BaseRepair<M>> extends Model<M> implements IBean {
	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getInt("id");
	}

	public void setRepairId(Integer repairId) {
		set("repairId", repairId);
	}

	public Integer getRepairId() {
		return getInt("repairId");
	}

	public void setRepairMan(String repairMan) {
		set("repairMan", repairMan);
	}

	public String getRepairMan() {
		return getStr("repairMan");
	}

	public void setCompleteTime(java.util.Date completeTime) {
		set("completeTime", completeTime);
	}
	
	public java.util.Date getCompleteTime() {
		return get("completeTime");
	}

	public void setExpenseTime(java.util.Date expenseTime) {
		set("expenseTime", expenseTime);
	}
	
	public java.util.Date getExpenseTime() {
		return get("expenseTime");
	}

}
