package com.hy.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

import java.util.Date;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePurchaseTaskDetail<M extends BasePurchaseTaskDetail<M>> extends Model<M> implements IBean {
	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getInt("id");
	}

	public void setTaskNum(Integer taskNum) {
		set("taskNum", taskNum);
	}

	public Integer getTaskNum() {
		return getInt("taskNum");
	}

	public void setPursureId(Integer pursureId) {
		set("pursureId", pursureId);
	}

	public Integer getPursureId() {
		return getInt("pursureId");
	}

	public void setNum(Integer num) {
		set("num", num);
	}

	public Integer getNum() {
		return getInt("num");
	}

	public void setDeviceName(String deviceName) {
		set("deviceName", deviceName);
	}

	public String getDeviceName() {
		return getStr("deviceName");
	}

	public void setUserId(int userId) {
		set("userId", userId);
	}

	public int getUserId() {
		return getInt("userId");
	}

	public void setUnit(String unit) {
		set("unit", unit);
	}

	public String getUnit() {
		return getStr("unit");
	}

	public void setBuget(String buget) {
		set("buget", buget);
	}

	public String getBuget() {
		return getStr("buget");
	}

	public void setSource(String source) {
		set("source", source);
	}

	public String getSource() {
		return getStr("source");
	}

	public void setParameters(String parameters) {
		set("parameters", parameters);
	}

	public String getParameters() {
		return getStr("parameters");
	}


}
