package com.hy.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseInstall<M extends BaseInstall<M>> extends Model<M> implements IBean {
	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getInt("id");
	}

	public void setInstallId(String installId) {
		set("installId", installId);
	}

	public String getInstallId() {
		return getStr("installId");
	}

	public void setInstallMan(String installMan) {
		set("installMan", installMan);
	}

	public String getInstallMan() {
		return getStr("installMan");
	}

	public void setInstallTime(java.util.Date installTime) {
		set("installTime", installTime);
	}
	
	public java.util.Date getInstallTime() {
		return get("installTime");
	}

	public void setAppearTime(java.util.Date appearTime) {
		set("appearTime", appearTime);
	}
	
	public java.util.Date getAppearTime() {
		return get("appearTime");
	}

}
