package com.hy.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLeavestockDetail<M extends BaseLeavestockDetail<M>> extends Model<M> implements IBean {
	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getInt("id");
	}

	public void setFileNumber(String fileNumber) {
		set("fileNumber", fileNumber);
	}

	public String getFileNumber() {
		return getStr("fileNumber");
	}

	public void setLeaveId(Integer leaveId) {
		set("leaveId", leaveId);
	}

	public Integer getLeaveId() {
		return getInt("leaveId");
	}

	public void setLeaveDate(String leaveDate) {
		set("leaveDate", leaveDate);
	}

	public String getLeaveDate() {
		return getStr("leaveDate");
	}

	public void setLeavenum(Integer leavenum) {
		set("leavenum", leavenum);
	}

	public Integer getLeavenum() {
		return getInt("leavenum");
	}

	public void setDeviceName(String deviceName) {
		set("deviceName", deviceName);
	}

	public String getDeviceName() {
		return getStr("deviceName");
	}

	public void setDeviceClassName(String deviceClassName) {
		set("deviceClassName", deviceClassName);
	}

	public String getDeviceClassName() {
		return getStr("deviceClassName");
	}

}
